spring:
  application:
    name: config-server
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/TonyHC/Photo-Services-Config-Server
          username: TonyHC
          password: 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
          clone-on-start: true
        native:
          search-locations: file:///${user.home}/Desktop/Microservices/others/photo-services-config-server-native-file-system-backend
  profiles:
    active: native
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    addresses: amqp://localhost:5672

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh

encrypt:
#  key: someRandomD1mmyK3y
  key-store:
    location: file:///${user.home}/Desktop/Microservices/others/apiEncryptionKey.jks
    password: ul92lff8lop29
    alias: apiEncryptionKey