spring:
  application:
    name: config-server
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/TonyHC/Photo-Services-Config-Server
          username: TonyHC
          password: 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
          clone-on-start: true
        native:
          search-locations: classpath:native-file-system-backend
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    addresses: amqp://rabbitmq:5672

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh

encrypt:
  #  key: someRandomD1mmyK3y
  key-store:
    location: classpath:key-store/apiEncryptionKey.jks
    password: ul92lff8lop29
    alias: apiEncryptionKey