spring:
  application:
    name: config-server
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/TonyHC/Photo-Services-Config-Server
          username:
          password:
          clone-on-start: true
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    addresses: amqp://localhost:5672

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh