apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/bootstrap/kafka/*
      - ./k8s/bootstrap/postgres/customer/*
      - ./k8s/bootstrap/postgres/fraud/*
      - ./k8s/bootstrap/postgres/notification/*
      - ./k8s/bootstrap/rabbitmq/*
      - ./k8s/bootstrap/zipkin/*
      - ./k8s/bootstrap/zookeeper/*
      - ./k8s/services/customer/*
      - ./k8s/services/fraud/*
      - ./k8s/services/notification/*
build:
  local:
    push: false
  artifacts:
    - image: tchao98/customer
      context: customer
      jib:
        project: com.tonyhc:customer
    - image: tchao98/fraud
      context: fraud
      jib:
        project: com.tonyhc:fraud
    - image: tchao98/notification
      context: notification
      jib:
        project: com.tonyhc:notification