spring:
  application:
    name: eureka-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        initialInterval: 3000
        multiplier: 1.5
        maxInterval: 5000
        maxAttempts: 10
  config:
    import: optional:configserver:http://config-server:8888

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false