spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: http://user/
          predicates:
            - Path=/api/v1/users/**
  config:
    import: optional:configserver:http://localhost:8888
  main:
    web-application-type: reactive
  rabbitmq:
    addresses: amqp://localhost:5672
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true