spring:
  application:
    name: album
  devtools:
    restart:
      enabled: true
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true