spring:
  application:
    name: album
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        initialInterval: 3000
        multiplier: 1.5
        maxInterval: 5000
        maxAttempts: 10
      profile: docker
  config:
    import: optional:configserver:http://config-server:8888
  devtools:
    restart:
      enabled: true
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8084

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: eureka-server

logging:
  file:
    name: album.log