spring:
  application:
    name: album
  config:
    import: optional:configserver:http://localhost:8888
  devtools:
    restart:
      enabled: true
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8084

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  file:
    name: logs/album.log